apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh-helm.fullname" .}}-filebeat-config
  labels:
{{ include "wazuh-helm.labels" . | indent 4 }}
data:
  filebeat.yml: |
    # Wazuh - Filebeat configuration file
    filebeat.modules:
      - module: wazuh
        alerts:
          enabled: true
        archives:
          enabled: false

    setup.template.json.enabled: true
    setup.template.json.path: '/etc/filebeat/wazuh-template.json'
    setup.template.json.name: 'wazuh'
    setup.template.overwrite: true
    setup.ilm.enabled: false
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_URL}']
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      ssl.verification_mode: none
      ssl.certificate_authorities: ['/etc/ssl/root-ca.pem']
      ssl.certificate: '/etc/ssl/filebeat.pem'
      ssl.key: '/etc/ssl/filebeat.key'
