# Copyright (C) 2021 Wazuh Inc.
# Copyright (C) 2021 Breakpoint Labs, LLC
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh authd password secret

{{- if not .Values.global.secrets.authd.name }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: {{ .Release.Namespace }}
data:
  authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded
{{- end }}
