# Copyright (C) 2021 Breakpoint Labs, LLC
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Default values for wazuh-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  esHost: 'https://wazuh-elasticsearch-0.wazuh-elasticsearch:9200'
  sslVerification: 'none'
  elasticCreds:
    # Creates a default secret with u/p of 'admin:admin' if blank
    name: ""

  # Choose between "plain", "json", or "plain,json" for the format of internal logs
  loggingFormat: plain

  # Deploys placeholder secrets if not specified
  secrets:
    filebeat:
      enabled: false
      name: ""
    # Creates a default secret with password "password" if blank
    authd: 
      name: ""
    # Creates a cluster key if blank
    clusterKey: 
      name: ""
    # Creates a default API credential
    apiCred: 
      name: ""

  service:
    type: ClusterIP
    port: 1516

  config:
    ossec.conf: ""

master:
  replicaCount: 1

  image:
    repository: "wazuh/wazuh-odfe"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "4.2.0"

  service:
    type: ClusterIP

  # storageClass: 'hostpath'
  storage: 500Mi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 512Mi

  labels: {}

  sys_chroot:
    enabled: false

  nodeSelector: {}

  tolerations: []

  affinity: {}

worker:
  replicaCount: 1

  image:
    repository: "wazuh/wazuh-odfe"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "4.2.0"

  service:
    type: ClusterIP

  # storageClass: 'hostpath'
  storage: 500Mi
  
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 512Mi

  sys_chroot:
    enabled: false

  # storageClass: 'hostpath'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
